language: php

php:
  # - '5.6'
  #- '7.0'
   - '7.1'

before_script:


script:
  - vendor/bin/phpmd app text codesize design naming unusedcode
  - vendor/bin/phpunit --testdox --coverage-text tests

