sudo: false
language: php

php:
  #- 5.6
  #- 7.0
  - 7.1
env:
  #- LARAVEL_VERSION=5.1.*
  #- LARAVEL_VERSION=5.2.*
  - LARAVEL_VERSION=5.3.*
  #- LARAVEL_VERSION=5.4.*

before_script:
  - cp "Code Content"/.env.travis "Code Content"/.env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer require "laravel/framework:${LARAVEL_VERSION}"
  - php "Code Content"/artisan key:generate
  - php "Code Content"/artisan migrate --seed
  
script:
  - vendor "Code Content"/bin/phpmd app text codesize design naming unusedcode
  - vendor "Code Content"/bin/phpunit --testdox --coverage-text tests

matrix:
  fast_finish: true
