sudo: false
language: php

php:
  #- 5.6
  #- 7.0
  - 7.1
env:
  #- LARAVEL_VERSION=5.1.*
  #- LARAVEL_VERSION=5.2.*
  - LARAVEL_VERSION=5.3.*
  #- LARAVEL_VERSION=5.4.*

before_script:
  - cd ./"Code Content"
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer require "laravel/framework:${LARAVEL_VERSION}"
  - php artisan key:generate
  - php artisan migrate --seed
  
script:
  - php artisan migrate --seed
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
  
after_script:
  - php vendor/bin/coveralls -v

matrix:
  fast_finish: true
